config yml

diff --git a/.github/workflows/ci_test.yml b/.github/workflows/ci_test.yml
--- a/.github/workflows/ci_test.yml
+++ b/.github/workflows/ci_test.yml
@@ -23,7 +23,7 @@ jobs:
           python -m pip install --upgrade pip
           pip install pytest coverage
           if [ -f requirements.txt ]; then
-            pip install -r requirements_filtered.txt || echo "Some packages failed to install, continuing anyway"
+            pip install -r requirements.txt || echo "Some packages failed to install, continuing anyway"
           fi
 
       - name: Check for test files
